# Source: https://blog.simos.info/how-to-easily-run-graphics-accelerated-gui-apps-in-lxd-containers-on-your-ubuntu-desktop
description: GUI packages and cloud init config 
config:
  user.user-data: |
    #cloud-config
    runcmd:
    - 'sed -i "s/; enable-shm = yes/enable-shm = no/g" /etc/pulse/client.conf'
    - 'echo export PULSE_SERVER=unix:/tmp/.pulse-native | tee --append /home/ubuntu/.profile'
    packages:
    - x11-apps
    - mesa-utils
    - pulseaudio
